name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ["${{ matrix.arch }}" ]
    strategy:
      matrix: 
        arch: [x86_64, aarch64]
      fail-fast: false
    
    steps:
    - uses: actions/checkout@main

    - name: Publish to registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nubificus/vaccel-deps
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: TOKEN=${{ secrets.NBFC_BUILDER_TOKEN }}
        tags: ${{ matrix.arch }}
        dockerfile: Dockerfile.${{ matrix.arch }}

  create_manifest:
    runs-on: [self-hosted, aarch64]
    needs: build

    steps:
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create manifest
        run: |
          docker manifest rm nubificus/vaccel-deps:latest
          docker manifest create nubificus/vaccel-deps:latest \
            --amend nubificus/vaccel-deps:x86_64 \
            --amend nubificus/vaccel-deps:aarch64
          docker manifest push nubificus/vaccel-deps:latest
