name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ["${{ matrix.arch }}" ]
    strategy:
      matrix: 
        arch: [x86_64, aarch64]
      fail-fast: false
    
    steps:
    - uses: actions/checkout@main

    - name: Publish to registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nubificus/vaccel-deps
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: TOKEN=${{ secrets.NBFC_BUILDER_TOKEN }}
        tags: ${{ matrix.arch }}
        dockerfile: Dockerfile.${{ matrix.arch }}
