name: Docker Image CI

on:
  push:
    branches: [ main, aarch64 ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ["${{ matrix.arch }}" ]
    strategy:
      matrix: 
        arch: [X64, aarch64]
      fail-fast: false
    steps:
    - uses: actions/checkout@main

    - name: Set Dockerfile name & Tags
      id: set-dockerfile-name
      run: |
        if [[ "${{ matrix.arch }}" == "X64" ]]
        then
          Dockerfile="Dockerfile"
          tag="x86_64"
          echo "::set-output name=dfile::$Dockerfile"
          echo "::set-output name=atag::$tag"
        else
          Dockerfile="Dockerfile.arm64"
          tag="arm64"
          echo "::set-output name=dfile::$Dockerfile"
          echo "::set-output name=atag::$tag"
        fi
        
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name:  nubificus/vaccel-deps
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: TOKEN=${{ secrets.NBFC_BUILDER_TOKEN }}
        tags: "${{ steps.set-dockerfile-name.outputs.atag }}"
        dockerfile: ${{ steps.set-dockerfile-name.outputs.dfile }}
